### ISSUE TITLE
Connect Supabase to mad hacker project

### ISSUE THREAD

**Issue by KiranGadhavi** [SchoolOfCode/final-project-the-mad-hackers#7]
```[tasklist]
### Tasks
- [x] Create file in mad hacker project to connect our supabase
- [x] Install Supabase libraries
- [x] Add code and apiKey, URL, and create functionality for connecting to supabase
```
